long = input("请输入长度 （单位：米）：")
long =int(long)
print(f"长度是{long}米，等于是{long*100}厘米，等于是{long*1000}毫米")
score_math = input("请输入数学成绩：")
score_math =float(score_math)
score_chinese= input("请输入语文成绩：")
score_chinese =float(score_chinese)
score_english = input("请输入英语成绩：")
score_english =float(score_english)
average_score=(score_english+score_chinese+score_math)/3
print(f"平均成绩是{average_score}")
total_score=score_english+score_math+score_chinese
print(f"总成绩是{total_score}")
name=input("请输入姓名:")
age=input("请输入年龄：")
age=int(age)
major=input("请输入专业：")
id=input("请输入学号：")
print("====================")
print(f"姓名：{name}")
print(f"年龄：{age}")
print(f"专业：{major}")
print(f"学号：{id}")
print("====================")